import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState, useEffect, useCallback } from 'react';
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();

  //console.log(supabase);
  const [fetchError, setFetchError] = useState(null);
  const [datos, setDatos] = useState(null);

  //----------------------------------------------------------------
  const [formInput, setFormInput] = useState({});
  const [errorDatosInput, setErrorDatosInput] = useState({});
  const [equipo, setEquipo] = useState([]);

  const handleOnInputChange = useCallback(
    (event) => {
      const { value, name, id, checked} = event.target;

      setFormInput({
        ...formInput,
        [name]: value,
      });

      //VALIDACIÓN INPUT EQUIPO
      if (name == "equipo"){     
        var temp = equipo;
        
        if (checked == false){
          temp.push(value);
        }
        
        if (checked == false){
          const indice = temp.indexOf(value);
          if (indice > -1) {
            temp.splice(indice, 1);
          }
        }
        
        setEquipo(temp);

        setFormInput({
          ...setFormInput,
          [name]: temp,
        });
      }

    },
    [formInput, setFormInput]
  );

  //----------------------------------------------------------------

  function incluye(arreglo, buscar) {
    if (arreglo != undefined){
      var encontrado = false;
      var arreglo_temp = Array.from(arreglo);

      for (let i = 0; i < arreglo_temp.length; i++) {
        if (arreglo_temp[i] == buscar){
          encontrado = false;
          break;
        }
      }  
      return encontrado;
    }
    else{
      return false;
    }
  }

  return (
    <div className="bg-stone-100 w-full h-screen" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="form-control py-10 px-16 bg-blue-100 rounded-lg shadow-lg">
          <h2 className="text-3xl font-bold mb-10">
            Agregar Ejercicio
          </h2>

          {/*CAMPO Nombre ---------------------------- */}
          <input name="nombre" value={formInput.nombre || ""} onChange={handleOnInputChange} type="text" placeholder="Nombre" className={"input input-lg mt-2 " +  (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error")  ? "input-error" : "input-success") : " ")}/>
          
          <label className="label">
            <span className="label-text-alt text-red-500">{incluye(errorDatosInput.correo, "error")  ? "Use un correo válido." : ""}</span>
          </label>

          {/* SELECT GRUPO MUSCULAR */}
          <div className="form-control mt-4 mb-4 lg:mb-7">
              <select name="musculo" id="musculo" onChange={handleOnInputChange} className="select select-secondary text-secondary text-xl py-4 h-full border-0 font-normal rounded-xl shadow-md" defaultValue={formInput.musculo}>
                <option id="Todos" value="Todos" hidden>Musculo Primario</option>
                <option id="Abdomen" value="Abdomen">Abdomen</option>
                <option id="Oblicuos" value="Oblicuos">Oblicuos</option>
                <option id="Antebrazos" value="Antebrazos">Antebrazos</option>
                <option id="Biceps" value="Biceps">Biceps</option>
                <option id="Triceps" value="Triceps">Triceps</option>
                <option id="Hombros" value="Hombros">Hombros</option>
                <option id="Trapecio" value="Trapecio">Trapecio</option>
                <option id="Trapecio Medio" value="Trapecio Medio">Trapecio Medio</option>
                <option id="Pecho" value="Pecho">Pecho</option>
                <option id="Cuadriceps" value="Cuadriceps">Cuadriceps</option>
                <option id="Pantorrillas" value="Pantorrillas">Pantorrillas</option>
                <option id="Isquiotibiales" value="Isquiotibiales">Isquiotibiales</option>
                <option id="Dorsales" value="Dorsales">Dorsales</option>
                <option id="Gluteos" value="Gluteos">Gluteos</option>
                <option id="Espalda Baja" value="Espalda Baja">Espalda Baja</option>
              </select>
            </div>

          {/*CAMPO Otros Musculos ---------------------------- */}
          <div className="collapse collapse-arrow bg-base-100 rounded-xl shadow-md mb-7">
            <input type="checkbox" /> 
            <div className="collapse-title text-xl text-lefty">
              Otros Musculos
            </div>
            <div className="collapse-content"> 
            <div className="divider m-0"></div>

              {/* CHECKBOX Otros Musculos */}
              <div className="flex flex-row flex-wrap form-control">
                <div className="w-full lg:w-1/3 lg:m-auto">
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Ninguno</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Ninguno") : false} className="toggle toggle-secondary" value="Ninguno" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banda de resistencia</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banda de resistencia") : false} className="toggle toggle-secondary" value="Banda de resistencia" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banda de suspensión</span>
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banda de suspension") : false} className="toggle toggle-secondary" value="Banda de suspension" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barra</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barra") : false} className="toggle toggle-secondary" value="Barra" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barra Z</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barra Z") : false} className="toggle toggle-secondary" value="Barra Z" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barras (dominadas, paralelas)</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barras (dominadas, paralelas)") : false} className="toggle toggle-secondary" value="Barras (dominadas, paralelas)" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Mancuernas</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Mancuernas") : false} className="toggle toggle-secondary" value="Mancuernas" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                </div>

                <div className="w-full lg:w-1/3 lg:m-auto">
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Pesa rusa</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Pesa rusa") : false} className="toggle toggle-secondary" value="Pesa rusa" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Placa de peso</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Placa de peso") : false} className="toggle toggle-secondary" value="Placa de peso" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Máquinas en GYM</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Maquinas en GYM") : false} className="toggle toggle-secondary" value="Maquinas en GYM" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco plano</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco plano") : false} className="toggle toggle-secondary" value="Banco plano" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco declinado</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco declinado") : false} className="toggle toggle-secondary" value="Banco declinado" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco inclinado</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco inclinado") : false} className="toggle toggle-secondary" value="Banco inclinado" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Cuerda</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Cuerda") : false} className="toggle toggle-secondary" value="Cuerda" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                </div>
              </div>

              <div className="flex flex-col items-center mb-3 mt-5">
                <div className="flex flex-row flex-wrap items-center">
                  <button
                  onClick={() => {
                    var temp = ["Ninguno","Banda de resistencia","Banda de suspension","Barra","Barra Z","Barras (dominadas, paralelas)","Mancuerna","Mancuernas","Pesa rusa","Placa de peso","Maquinas en GYM","Banco plano","Banco declinado","Banco inclinado","Cuerda"]
                    setEquipo(temp);
                    setFormInput({equipo: temp})}} 
                    className="btn btn-secondary w-3/4 mx-auto">Activar todos
                  </button>
                  <button
                  onClick={() => {
                    var temp = []
                    setEquipo(temp);
                    setFormInput({equipo: temp})}} 
                    className="btn mt-4 w-3/4 mx-auto">Desactivar todos
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/*CAMPO equipo ---------------------------- */}
          <div className="collapse collapse-arrow bg-base-100 rounded-xl shadow-md mb-7">
            <input type="checkbox" /> 
            <div className="collapse-title text-xl text-left">
              Equipo
            </div>
            <div className="collapse-content"> 
            <div className="divider m-0"></div>

              {/* CHECKBOX TOGGLE EQUIPO */}
              <div className="flex flex-row flex-wrap form-control">
                <div className="w-full lg:w-1/3 lg:m-auto">
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Ninguno</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Ninguno") : false} className="toggle toggle-secondary" value="Ninguno" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banda de resistencia</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banda de resistencia") : false} className="toggle toggle-secondary" value="Banda de resistencia" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banda de suspensión</span>
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banda de suspension") : false} className="toggle toggle-secondary" value="Banda de suspension" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barra</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barra") : false} className="toggle toggle-secondary" value="Barra" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barra Z</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barra Z") : false} className="toggle toggle-secondary" value="Barra Z" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Barras (dominadas, paralelas)</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Barras (dominadas, paralelas)") : false} className="toggle toggle-secondary" value="Barras (dominadas, paralelas)" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Mancuernas</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Mancuernas") : false} className="toggle toggle-secondary" value="Mancuernas" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                </div>

                <div className="w-full lg:w-1/3 lg:m-auto">
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Pesa rusa</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Pesa rusa") : false} className="toggle toggle-secondary" value="Pesa rusa" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Placa de peso</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Placa de peso") : false} className="toggle toggle-secondary" value="Placa de peso" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Máquinas en GYM</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Maquinas en GYM") : false} className="toggle toggle-secondary" value="Maquinas en GYM" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco plano</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco plano") : false} className="toggle toggle-secondary" value="Banco plano" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco declinado</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco declinado") : false} className="toggle toggle-secondary" value="Banco declinado" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Banco inclinado</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Banco inclinado") : false} className="toggle toggle-secondary" value="Banco inclinado" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                  <label className="cursor-pointer label">
                    <span className="label-text mx-4">Cuerda</span> 
                    <input type="checkbox" checked={formInput.equipo ? incluye(formInput.equipo, "Cuerda") : false} className="toggle toggle-secondary" value="Cuerda" id="equipo" name="equipo" onChange={handleOnInputChange} />
                  </label>
                </div>
              </div>

              <div className="flex flex-col items-center mb-3 mt-5">
                <div className="flex flex-row flex-wrap items-center">
                  <button
                  onClick={() => {
                    var temp = ["Ninguno","Banda de resistencia","Banda de suspension","Barra","Barra Z","Barras (dominadas, paralelas)","Mancuerna","Mancuernas","Pesa rusa","Placa de peso","Maquinas en GYM","Banco plano","Banco declinado","Banco inclinado","Cuerda"]
                    setEquipo(temp);
                    setFormInput({equipo: temp})}} 
                    className="btn btn-secondary w-3/4 mx-auto">Activar todos
                  </button>
                  <button
                  onClick={() => {
                    var temp = []
                    setEquipo(temp);
                    setFormInput({equipo: temp})}} 
                    className="btn mt-4 w-3/4 mx-auto">Desactivar todos
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/*CAMPO recomendaciones ---------------------------- */}   
          <textarea name="recomendaciones" value={formInput.recomendaciones || ""} onChange={handleOnInputChange} placeholder="Recomendaciones" className={"textarea textarea-success text-lg border-2 mt-2 " +  (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error")  ? "input-error" : "input-success") : " ")}></textarea>

          <label className="label">
            <span className="label-text-alt text-red-500">{incluye(errorDatosInput.correo, "error")  ? "Use un correo válido." : ""}</span>
          </label>

          {/*CAMPO errores ---------------------------- */}
          <textarea name="errores" value={formInput.errores || ""} onChange={handleOnInputChange} placeholder="Errores comunes" className={"textarea textarea-warning text-lg border-2 mt-2 " +  (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error")  ? "input-error" : "input-success") : " ")}></textarea>

          <label className="label">
            <span className="label-text-alt text-red-500">{incluye(errorDatosInput.correo, "error")  ? "Use un correo válido." : ""}</span>
          </label>

          {/*CAMPO imagen ---------------------------- */}
          <input name="imagen" type="file" className="file-input file-input-bordered file-input-secondary w-full max-w-xs" />

          {
            (datos) ? 
            (
              <div className="alert alert-success font-bold text-white">
                <div>
                  <span>
                    ¡Se agregó correctamente!
                  </span>
                </div>
              </div>
            )
            : ""
          }

          {
            (fetchError) ? 
            (
              <div className="alert alert-error font-bold text-white">
                <div>
                  <span>
                    Ocurrió un error.
                  </span>
                </div>
              </div>
            )
            : ""
          }
          
          {/*BOTÓN ENVIAR FORMULARIO ---------------- */}
          <button className={"btn btn-secondary btn-lg m-6 " + (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error") || incluye(errorDatosInput.password, "error") || incluye(errorDatosInput.confirmarPassword, "error") ? "btn-disabled" : " ") : " ")} onClick={() => {}}>
            Enviar
          </button>
        </div>

        <button
          onClick={() => router.push('/biblioteca')}
          className="btn btn-ghost btn-lg mt-10"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
          &nbsp;Volver a Biblioteca
        </button>
      </main>

      <footer className={styles.footer}>
        <p className="font-light">
          {'Powered by '}
          <span className="animate-pulse font-bold text-fuchsia-500">
            {'Evoltfit'}
          </span>
        </p>
      </footer>
    </div>
  );
}
