import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Navbar from "./Componentes/Navbar";
import Footer from "./Componentes/Footer";
import supabase from "../config/supabaseClient";

export default function Home() {
  const router = useRouter();
  const [sesion, setSesion] = useState(null);
  const [ejercicios, setEjercicios] = useState(null);
  const query = router.query;
  const name = query.name;
  console.log(name);

  useEffect(() => {
    getEjercicios();
  }, []);

  async function getEjercicios() {
    const data = await supabase.from("prueba_ejercicios").select("*");
    setEjercicios(data.data);
    console.log(ejercicios);
  }

  return (
    <div className="bg-stone-100 w-full" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <h2 className="text-2xl text-left text-center">
          Biblioteca de Ejercicios Filtrada - {name}
        </h2>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
       
      </main>
      <Footer></Footer>
    </div>
  );
}
