import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className="font-thin text-2xl">
          {"Correo confirmado :)"}
          <br />
          
        </h2>

        <button
          onClick={() => router.push('/login')}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-10"
        >
          {'Iniciar Sesión'}
        </button>
      </main>

      <footer className={styles.footer}>
        <p className="font-light">
          {'Powered by '}
          <span className="animate-pulse font-bold text-fuchsia-500">
            {'Evoltfit'}
          </span>
        </p>
      </footer>
    </div>
  );
}
