import React from "react";
import Navbar from "/Components/Navbar";
import Footer from "/Components/Footer";
import Head from "next/head";
import { useState, useEffect } from "react";
import supabase from "/config/supabaseClient";
import Link from "next/link";

export default function Home() {
  const [sesion, setSesion] = useState(null);
  const [flag, setFlag] = useState(false);
  const [resultado, setResultado] = useState(null);

  useEffect(() => {
    handleSesion();
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
    if (flag == true) {
      setFlag(false);

      if (sesion) {
        console.log("El usuario conectado es:" + sesion.user.id);
        async function getPlan() {
          console.log("Entramos a getPlan");
          let { data: sus_pagos, error } = await supabase
            .from("sus_pagos")
            .select("activo")
            .eq("id_usuario", sesion.user.id);

          if (sus_pagos.length == 0) {
            console.log("Este usuario no tiene plan");
            setResultado(0);
          } else {
            console.log("Este usuario si tiene un plan");
            console.log(sus_pagos[0].activo);
            setResultado(sus_pagos[0].activo);
          }
        }
        getPlan();
      } else {
        console.log("No hay una sesion iniciada");
      }
    }
    setFlag(true);
  }, [flag]);

  const handleSesion = async () => {
    const { data, error } = await supabase.auth.getSession();

    if (data.session) {
      setSesion(data.session);
      console.log(data);
    } else {
      setSesion(null);
      console.log("No hay Sesión " + error);
      console.log(data);
    }
  };

  return (
    <div className="bg-blue-50 w-full">
      <Head>
        <title>EvoltFit - Herramientas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <br />
        <br />
        <br />
        <br />
        {resultado == 0 ? (
          <section className="bg-blue-50">
            <div className="container px-6 py-10 mx-auto">
              <h1 className="text-3xl font-semibold text-center text-gray-800 lg:text-4xl dark:text-white">
                Todo lo que necesitas en un solo lugar
              </h1>

              <p className="mt-4 text-center text-gray-500 dark:text-gray-300">
                Te ofrecemos un repertorio de herramientas que te serviran para
                hacer un seguimiento de tu progreso.
              </p>

              <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="rutina.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Generador de rutinas automático
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="cal.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Contador de calorías
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="registro.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Registro de series y repeticiones
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="progreso.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Visualizador de progreso
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Máximo peso para una repetición
                      </h2>
                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran hover:text-lime-400">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Sobrecarga progresiva
                      </h2>
                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran hover:text-lime-400">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Método Bilbo
                      </h2>
                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </section>
        ) : resultado == 1 ? (
          <section className="bg-blue-50">
            <div className="container px-6 py-10 mx-auto">
              <h1 className="text-3xl font-semibold text-center text-gray-800 lg:text-4xl dark:text-white">
                Todo lo que necesitas en un solo lugar
              </h1>

              <p className="mt-4 text-center text-gray-500 dark:text-gray-300">
                Te ofrecemos un repertorio de herramientas que te serviran para
                hacer un seguimiento de tu progreso.
              </p>

              <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="rutina.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Generador de rutinas automático
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="cal.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Contador de calorías
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="registro.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Registro de series y repeticiones
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="progreso.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Visualizador de progreso
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Máximo peso para una repetición
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Sobrecarga progresiva
                      </h2>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="/">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Método Bilbo
                      </h2>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </section>
        ) : (
          <section className="bg-blue-50">
            {/*Renderizado si no hay sesion iniciada*/}
            <div className="container px-6 py-10 mx-auto">
              <h1 className="text-3xl font-semibold text-center text-gray-800 lg:text-4xl dark:text-white">
                Todo lo que necesitas en un solo lugar
              </h1>

              <p className="mt-4 text-center text-gray-500 dark:text-gray-300">
                Te ofrecemos un repertorio de herramientas que te serviran para
                hacer un seguimiento de tu progreso.
              </p>

              <div className="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 md:grid-cols-2 xl:grid-cols-3">
                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="rutina.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Generador de rutinas automático
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="cal.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Contador de calorías
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Acceso directo
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="registro.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Registro de series y repeticiones
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="progreso.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Visualizador de progreso
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Máximo peso para una repetición
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>

                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran hover:text-lime-400">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Sobrecarga progresiva
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>
                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran hover:text-lime-400">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>

                <div className="overflow-hidden bg-cover rounded-lg cursor-pointer h-96 group bg-internal-img">
                  <Link href="../registro">
                    <div className="flex flex-col justify-center w-full h-full px-8 py-4 transition-opacity duration-700 xl:opacity-0 backdrop-blur-sm bg-blue-900/60 group-hover:opacity-100">
                      <center>
                        <div className="h-20 w-20">
                          <img src="metodo.png"></img>
                        </div>
                      </center>
                      <h2 className="mt-12 text-2xl text-white font-bold">
                        Método Bilbo
                      </h2>
                      <p className="mt-2 text-lg tracking-wider text-blue-400 font-catamaran">
                        Necesitas una cuenta para poder utilizarla
                      </p>

                      <p className="animate-pulse mt-2 text-lg tracking-wider text-lime-500 font-catamaran">
                        Necesitas una suscripción EvoltFit Plus para poder
                        utilizarla
                      </p>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </section>
        )}

        <br />
        <br />
        <br />
        <br />
        <br />
      </main>
      <Footer></Footer>
    </div>
  );
}
