import React from 'react';
import Navbar from './Componentes/Navbar';
import Footer from "./Componentes/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  
  
    return (
      <div className = "bg-blue-100 w-full h-screen">
        <Head>
          <title>EvoltFit - Herramientas</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <main className={styles.main}>
        <h1 className="font-thin text-2xl">
          {"Bienvenido a... "}
          <br />
          <span className="animate-pulse text-8xl text-blue-600 font-normal">
            la página herramientas
          </span>
        </h1>
        </main>
        <Footer></Footer>
      </div>
    );
  }