import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState, useEffect } from 'react';
import Navbar from './Componentes/Navbar';
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();
  const [sesion, setSesion] = useState(null);

  useEffect(() => {
    handleSesion()
  
  }, [])

  const handleSesion = async () => {

    const { data, error } = await supabase.auth.getSession()

    if(data.session){
      setSesion(data.session);
      console.log(data);
    } 
    else {
      setSesion(null);
      console.log("No hay Sesión " + error);
      console.log(data);
    }
  }

  const handleLogout = async () => {
    const { error } = await supabase.auth.signOut()
    
    if(error){
      console.log(error);
    }
    else{
      router.reload(window.location.pathname);
    }
  }

  return (
    <div className = "bg-stone-100 w-full h-screen">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        <h1 className="font-thin text-2xl">
          {"Bienvenido a... "}
          <br />
          {sesion ? 
            (
              <div>
                <span className="text-2xl text-blue-600 font-normal">
                  {"Bienvenido: " + sesion.user.email}
                </span>
                <button className="btn btn-error btn-lg m-6" onClick={handleLogout}>Cerrar Sesión</button>
              </div>
            )
            :
            (
              <span className="animate-pulse text-8xl text-blue-600 font-normal">
                la página de inicio
              </span>

            )
          }
        </h1>
        </main>
    </div>
   /* <div className={styles.container}>

      <main className={styles.main}>
        <h1 className="font-thin text-2xl">
          {"Bienvenido a... "}
          <br />
          <span className="animate-pulse text-8xl text-blue-600 font-normal">
            EvoltFit
          </span>
        </h1>

        <button
          onClick={() => router.push("/login")}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-10"
        >
          Login
        </button>
        <button
          onClick={() => router.push("/pruebafetch")}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-0"
        >
          Fetch base de Datos
        </button>
      </main>

      <footer className={styles.footer}>
        <p className="font-light">
          {"Powered by "}
          <span className="animate-pulse font-bold text-fuchsia-500">
            {"Evoltfit"}
          </span>
        </p>
      </footer>
    </div>*/

  );
}
