import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState, useEffect, useCallback } from 'react';
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();

  //console.log(supabase);
  const [fetchError, setFetchError] = useState(null);
  const [datos, setDatos] = useState(null);

  //----------------------------------------------------------------
  const [formInput, setFormInput] = useState({});
  const [errorDatosInput, setErrorDatosInput] = useState({});

  const handleOnInputChange = useCallback(
    (event) => {
      const { value, name } = event.target;

      setFormInput({
        ...formInput,
        [name]: value,
      });

    },
    [formInput, setFormInput]
  );

  //----------------------------------------------------------------
  const handleLogin = async () => {

    const { data, error } = await supabase.auth.signInWithPassword({
      email: formInput.correo,
      password: formInput.password,
    })

    if(error){
      setDatos(null);
      setFetchError('Error en el login.');
      console.log("Login fallido");
      console.log(error);
    } 
    else {
      setDatos(data);
      setFetchError(null);
      console.log("Login exitoso");
      console.log(data);
      router.push('/login')
    }
  }

  function incluye(arreglo, buscar) {
    if (arreglo != undefined){
      var encontrado = false;
      var arreglo_temp = Array.from(arreglo);

      for (let i = 0; i < arreglo_temp.length; i++) {
        if (arreglo_temp[i] == buscar){
          encontrado = true;
          break;
        }
      }  
      return encontrado;
    }
    else{
      return false;
    }
  }

  //console.log(datos);
  //console.log(fetchError);

  return (
    <div className={styles.container}>
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className="font-thin text-2xl">
          Login
        </h2>

        <div className="form-control w-full max-w-xs border-double border-4 p-6 m-6 border-gray-700 rounded-lg">
          {/*CAMPO CORREO ------------------------ */}
          <label className="label">
            <span className="label-text mt-6">{"Correo"}</span>
          </label>
          <input name="correo" value={formInput.correo || ""} onChange={handleOnInputChange} type="text" placeholder="Correo" className={"input input-bordered w-full max-w-xs " + (incluye(errorDatosInput.correo, "error")  ? "input-error" : " ")}/>

          {/*CAMPO CONTRASEÑA ------------------------ */}
          <label className="label">
            <span className="label-text mt-6">{"Password"}</span>
          </label>
          <input name="password" value={formInput.password || ""} onChange={handleOnInputChange} type="password" placeholder="Password" className={"input input-bordered w-full max-w-xs " + (incluye(errorDatosInput.password, "error")  ? "input-error" : " ")}/>
        
          <button className="btn btn-outline btn-success rounded-full m-6 mt-12" onClick={handleLogin}>Iniciar Sesión</button>
        
          <p>{datos ? "LOGIN EXITOSO" : ""}</p>
          <p>{datos ? datos.user.email : ""}</p>

          <p>{fetchError ? "LOGIN FALLIDO" : ""}</p>
        </div>


        <button
          onClick={() => router.push('/registro')}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-10"
        >
          Registrarme
        </button>

        <button
          onClick={() => router.push('/')}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-0"
        >
          Inicio
        </button>
      </main>

      <footer className={styles.footer}>
        <p className="font-light">
          {'Powered by '}
          <span className="animate-pulse font-bold text-fuchsia-500">
            {'Evoltfit'}
          </span>
        </p>
      </footer>
    </div>
  );
}
