import Head from "next/head";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import Typed from "react-typed";
import supabase from "../config/supabaseClient";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function MetodoBilbo() {

  useEffect(() => {
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  })

  return (
    <div className="bg-stone-100 w-full">
      <Head>
        <title>EvoltFit - Método Bilbo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <br />
      <br />
      <main>
      <section className="h-full bg-cover bg-internal-img6">
          <div className="flex flex-col min-h-screen bg-blue-600/30">
            <div className=" mt-32 lg:mt-0 container flex flex-col flex-1 px-6 py-12 mx-auto">
              <div className="flex-1 lg:flex lg:items-center lg:-mx-6">
                <div className="text-white lg:w-1/2 lg:mx-6">
                  <p className="text-7xl xl:text-9xl font-bebas tracking-widest">
                    Inside the Gym:
                  </p>
                </div>
                <div className="lg:w-1/2 lg:mx-6">
                  <Typed
                    strings={["Método Bilbo"]}
                    typeSpeed={150}
                    backSpeed={100}
                    className="text-6xl xl:text-8xl font-bebas animate-pulse tracking-widest text-white"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
        <br/>
        <br/>
        <br/>
        <h1 className="text-center mb-12 text-zinc-700 font-catamaran  xl:mb-14 text-3xl xl:text-5xl ">
        {"Conoce el método Bilbo"}
        </h1>
        <div className="grid place-items-center">
          <div className="w-9/12">
            <p className="text-center font-heebo text-base xl:text-lg">
            {"El Método Bilbo creado por Jesús Varela el mejor pressbanquista de España, consiste en ganar fuerza a través de la velocidad y explosividad manteniéndonos alejados de grandes pesos. Se consigue con series de entre 15 y 50 repeticiones. Se trata de conseguir la máxima efectividad en una única serie, acostumbrando al músculo a darlo todo en poco más de 30 segundos. Al igual que para un  velocista no tiene sentido pasar dos horas corriendo, para alguien que busque aumentar su fuerza y explosividad tampoco tiene sentido alargar las series y entrenamientos. Cuanto más cortos e intensos sean los entrenamientos mejores resultados obtendremos, sobremanera tratándose de deportistas naturales."}
            </p>
          </div>
        </div>
        
        <section className = "-mb-14">
          <div className="container px-6 py-12 mx-auto">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <div>
              <svg className="svg-icon" viewBox="0 0 20 20">
							<path fill="none" d="M9.917,0.875c-5.086,0-9.208,4.123-9.208,9.208c0,5.086,4.123,9.208,9.208,9.208s9.208-4.122,9.208-9.208
								C19.125,4.998,15.003,0.875,9.917,0.875z M9.917,18.141c-4.451,0-8.058-3.607-8.058-8.058s3.607-8.057,8.058-8.057
								c4.449,0,8.057,3.607,8.057,8.057S14.366,18.141,9.917,18.141z M13.851,6.794l-5.373,5.372L5.984,9.672
								c-0.219-0.219-0.575-0.219-0.795,0c-0.219,0.22-0.219,0.575,0,0.794l2.823,2.823c0.02,0.028,0.031,0.059,0.055,0.083
								c0.113,0.113,0.263,0.166,0.411,0.162c0.148,0.004,0.298-0.049,0.411-0.162c0.024-0.024,0.036-0.055,0.055-0.083l5.701-5.7
								c0.219-0.219,0.219-0.575,0-0.794C14.425,6.575,14.069,6.575,13.851,6.794z"></path>
						  </svg>
                <h1 className="mt-4 text-xl font-semibold text-gray-800">
                 {"No se alcanza el fallo"}
                </h1>

                <p className="mt-2 text-gray-500 font-heebo">
                {"El fallo total es un paso atrás, no es beneficioso. Siempre después de un fallo viene una pequeña perdida de rendimiento, por lo que es mejor evitar en lo posible llegar a fallar. Los entrenamientos que sistemáticamente buscan el fallo pueden ser soportables por gente que use química. Nadie natural puede ir al fallo todos los días en el gimnasio y esperar mejoras."}
                </p>
              </div>

              <div>
              <svg className="svg-icon" viewBox="0 0 20 20">
							<path fill="none" d="M9.917,0.875c-5.086,0-9.208,4.123-9.208,9.208c0,5.086,4.123,9.208,9.208,9.208s9.208-4.122,9.208-9.208
								C19.125,4.998,15.003,0.875,9.917,0.875z M9.917,18.141c-4.451,0-8.058-3.607-8.058-8.058s3.607-8.057,8.058-8.057
								c4.449,0,8.057,3.607,8.057,8.057S14.366,18.141,9.917,18.141z M13.851,6.794l-5.373,5.372L5.984,9.672
								c-0.219-0.219-0.575-0.219-0.795,0c-0.219,0.22-0.219,0.575,0,0.794l2.823,2.823c0.02,0.028,0.031,0.059,0.055,0.083
								c0.113,0.113,0.263,0.166,0.411,0.162c0.148,0.004,0.298-0.049,0.411-0.162c0.024-0.024,0.036-0.055,0.055-0.083l5.701-5.7
								c0.219-0.219,0.219-0.575,0-0.794C14.425,6.575,14.069,6.575,13.851,6.794z"></path>
						  </svg>
                <h1 className="mt-4 text-xl font-semibold text-gray-800">
               {"Superávit calórico"}
                </h1>

                <p className="mt-2 text-gray-500 font-heebo">
                {"Como en cualquier otro método de entrenamiento, si se quiere mejorar se tienen que hacer las progresiones en superávit calórico. Hay que ir incrementando el peso corporal mientras ajustamos las progresiones, volviendo a bajar de peso corporal al terminarlas, pero sin preocuparnos de perder marcas. Y repetir una y otra vez esto. Cada vez que terminemos la progresión ayudados con el aumento de peso corporal, habremos ganado masa muscular y fuerza."}
                </p>
              </div>

              <div>
              <svg className="svg-icon" viewBox="0 0 20 20">
							<path fill="none" d="M9.917,0.875c-5.086,0-9.208,4.123-9.208,9.208c0,5.086,4.123,9.208,9.208,9.208s9.208-4.122,9.208-9.208
								C19.125,4.998,15.003,0.875,9.917,0.875z M9.917,18.141c-4.451,0-8.058-3.607-8.058-8.058s3.607-8.057,8.058-8.057
								c4.449,0,8.057,3.607,8.057,8.057S14.366,18.141,9.917,18.141z M13.851,6.794l-5.373,5.372L5.984,9.672
								c-0.219-0.219-0.575-0.219-0.795,0c-0.219,0.22-0.219,0.575,0,0.794l2.823,2.823c0.02,0.028,0.031,0.059,0.055,0.083
								c0.113,0.113,0.263,0.166,0.411,0.162c0.148,0.004,0.298-0.049,0.411-0.162c0.024-0.024,0.036-0.055,0.055-0.083l5.701-5.7
								c0.219-0.219,0.219-0.575,0-0.794C14.425,6.575,14.069,6.575,13.851,6.794z"></path>
						  </svg>

                <h1 className="mt-4 text-xl font-semibold text-gray-800">
                 {"Retracción escapular"}
                </h1>

                <p className="mt-2 text-gray-500 font-heebo">
               {"La retracción idónea para realizar el press de banca de manera que nos permita mejorar en fuerza e hipertrofia además de evitar lesiones, es la que marca una postura en la cuál dejamos los hombros retrasados y el pectoral por delante de éstos. Con ello conseguimos un ligero arco lumbar y una moderada retracción escapular."}
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="py-16">
          <div className="container mx-auto py-2 flex flex-col lg:flex-row">
            <div className="flex flex-col justify-center text-center px-16 w-2/2 lg:w-1/2">
              <h2 className="text-3xl font-bold mb-5">{"Recomendaciones del creador"}</h2>
              <p className = "font-heebo">
              {"Jesús Varela te propone empezar cada entrenamiento sacando el máximo partido a tu primera serie. La primera serie se llama serie Bilbo y es la clave del progreso. En la serie Bilbo, se escoge un peso relativamente bajo y se busca sacar el máximo número de repeticiones posible. Hay que empujar siempre de una forma rápida y explosiva, pero evitando las trampas y rebotes en la medida de lo posible. Una vez que es completada la serie Bilbo, se anota el número de repes conseguidas, ya que el objetivo en el siguiente entrenamiento será superar dicho récord."}
              </p>
            </div>

            <div className="w-0 lg:w-1/2">
              <img
                className="skew-y-6 invisible lg:w-full lg:visible"
                src="preguntaBilbo2.jpg"
              />
            </div>
          </div>
        </section>
        
      </main>
      <br />
      <br />
      <br />
      <br />
      <Footer></Footer>
    </div>
  );
}
