import Head from "next/head";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Typed from "react-typed";

export default function Nosotros() {
  const router = useRouter();

  useEffect(() => {
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
    localStorage.setItem('bandera', 'false');
  }, []);

  return (
    <div className="bg-stone-100 w-full">
      <Head>
        <title>EvoltFit - Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <br />
        <br />
        <br />
        <br />

        <section className = "bg-cover bg-internal-img4">
          <div className = "flex flex-col min-h-screen">
          <Typed
            strings={[
              "Accesible",
              "Centralizado",
              "Intuitivo",
            ]}
            typeSpeed={150}
            backSpeed={100}
            className="absolute top-96 text-5xl text-center font-bebas text-white tracking-wider left-1/2 -translate-x-1/2 -translate-y-1/2 lg:text-8xl xl:top-96 "
            loop={true}
          />
          </div>
        </section>

        <br />
        <br />
        <br />
        <br />
        <div className="flex justify-center">
          <div className="grid grid-cols-1 gap-32 sm:grid-cols-2 sm:gap-x-14 lg:grid-cols-4 lg:gap-x-18 lg:w-auto ">
            <div>
              <div className="xl:grid xl:place-items-center">
                <div className="h-56 w-56">
                  <img
                    className="rounded-md shadow-2xl"
                    src="imgnos1.jpg"
                  ></img>
                </div>
              </div>
            </div>

            <div>
              <div className="xl:grid xl:place-items-center">
                <div className="h-56 w-56">
                  <img
                    className="rounded-md shadow-2xl"
                    src="imgnos2.jpg"
                  ></img>
                </div>
              </div>
            </div>

            <div>
              <div className="xl:grid xl:place-items-center">
                <div className="h-56 w-56">
                  <img
                    className="rounded-md shadow-2xl"
                    src="imgnos3.jpg"
                  ></img>
                </div>
              </div>
            </div>

            <div>
              <div className="xl:grid xl:place-items-center">
                <div className="h-56 w-56">
                  <img
                    className="rounded-md shadow-2xl"
                    src="imgnos4.jpg"
                  ></img>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        
        <section className="py-16">
          <div className="container mx-auto py-2 flex flex-col lg:flex-row">
            <div className="flex flex-col justify-center text-center px-16 lg:w-1/2">
              <h2 className="text-3xl font-bold mb-5">Misión</h2>
              <p>
              Ofrecer oportunidades y herramientas para mejorar la salud de todas y todos de manera creativa, innovadora y responsable, pero sobre todo personalizada implementando un sistema innovador enfocado al entrenamiento en cualquier parte.
              </p>
            </div>

            <div className="w-0 lg:w-1/2 relative">
              <img className="invisible lg:w-full lg:relative lg:z-10 lg:visible" src="bcmision.jpg" />
              <div className="invisible lg:bg-blue-600 lg:h-full lg:w-full lg:absolute lg:top-6 lg:-left-6 lg:visible"></div>
            </div>
          </div>
        </section>

        <section className="py-16">
          <div className="container mx-auto py-2 flex flex-col lg:flex-row">
            <div className="w-0 lg:w-1/2 relative">
              <img className="invisible lg:w-full lg:relative lg:z-10 lg:visible" src="bcvision.jpg" />
              <div className="invisible lg:bg-blue-600 lg:h-full lg:w-full lg:absolute lg:bottom-6 lg:-right-6 lg:visible"></div>
            </div>

            <div className="flex flex-col justify-center text-center px-16 lg:w-1/2">
              <h2 className="text-3xl font-bold mb-5">Visión</h2>
              <p>
              Construimos un futuro en el cual, la salud sea una de las prioridades más importantes de la población. Alentando a las personas a que no solo es posible ejercitarse en un gimnasio, sino también en casa.
              </p>
            </div>
          </div>
        </section>

        <section className="">
          <div className="container px-6 py-10 mx-auto">
            <h1 className="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl">
              Tenemos <br /> claros objetivos
            </h1>

            <div className="mt-2">
              <span className="inline-block w-40 h-1 bg-blue-500 rounded-full"></span>
              <span className="inline-block w-3 h-1 ml-1 bg-blue-500 rounded-full"></span>
              <span className="inline-block w-1 h-1 ml-1 bg-blue-500 rounded-full"></span>
            </div>

            <div className="mt-8 xl:mt-12 lg:flex lg:items-center">
              <div className="grid w-full grid-cols-1 gap-8 lg:w-1/2 xl:gap-16 md:grid-cols-2">
                <div className="space-y-3">
                  <span className="inline-block p-3 text-blue-500 bg-blue-100 rounded-xl">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-6 h-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                      />
                    </svg>
                  </span>

                  <h1 className="text-2xl font-semibold text-gray-700 capitalizee">
                    Estadísticas reales
                  </h1>

                  <p className="text-gray-500">
                    Las estadísticas y graficos que mostramos son de información generada por los ejercicios y
                    rutinas que lleves a cabo a lo largo del tiempo.
                  </p>
                </div>

                <div className="space-y-3">
                  <span className="inline-block p-3 text-blue-500 bg-blue-100 rounded-xl">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-6 h-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.656 7.343A7.975 7.975 0 0120 13a7.975 7.975 0 01-2.343 5.657z"
                      />
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9.879 16.121A3 3 0 1012.015 11L11 14H9c0 .768.293 1.536.879 2.121z"
                      />
                    </svg>
                  </span>

                  <h1 className="text-2xl font-semibold text-gray-700 capitalize">
                    Diseño entendible
                  </h1>

                  <p className="text-gray-500">
                    Estamos en constante evolución para poder entregarte una plataforma que cualquier persona pueda
                    entender y usar.
                  </p>
                </div>

                <div className="space-y-3">
                  <span className="inline-block p-3 text-blue-500 bg-blue-100 rounded-xl">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-6 h-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M11 4a2 2 0 114 0v1a1 1 0 001 1h3a1 1 0 011 1v3a1 1 0 01-1 1h-1a2 2 0 100 4h1a1 1 0 011 1v3a1 1 0 01-1 1h-3a1 1 0 01-1-1v-1a2 2 0 10-4 0v1a1 1 0 01-1 1H7a1 1 0 01-1-1v-3a1 1 0 00-1-1H4a2 2 0 110-4h1a1 1 0 001-1V7a1 1 0 011-1h3a1 1 0 001-1V4z"
                      />
                    </svg>
                  </span>

                  <h1 className="text-2xl font-semibold text-gray-700 capitalize">
                    Personalizado
                  </h1>

                  <p className="text-gray-500">
                    Con nuestras rutinas inteligentes puedes estar seguro que la rutina que te damos es la que mejorar
                    se apega a tus objetivos y a tu nivel.
                  </p>
                </div>

                <div className="space-y-3">
                  <span className="inline-block p-3 text-blue-500 bg-blue-100 rounded-xl">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-6 h-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"
                      />
                    </svg>
                  </span>

                  <h1 className="text-2xl font-semibold text-gray-700 capitalize">
                    Simple
                  </h1>

                  <p className="text-gray-500">
                    No usamos interfaces complejas ni sistemas robustos, todo lo que necesitas lo encuentras
                    de manera entendible, sin muchos botones y muy intuitivo.
                  </p>
                </div>
              </div>

              <div className="hidden lg:flex lg:w-1/2 lg:justify-center">
                <img
                  className="w-[28rem] h-[28rem] flex-shrink-0 object-cover xl:w-[34rem] xl:h-[34rem] rounded-full"
                  src="bcnosotros2.jpg"
                  alt=""
                />
              </div>
            </div>
          </div>
        </section>

        <br />
        <br />
        <br />
        <br />
      </main>
      <Footer></Footer>
    </div>
  );
}
