import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect, useCallback } from "react";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import supabase from "../config/supabaseClient";

export default function OneRepMax() {
  const router = useRouter();

  const [sesion, setSesion] = useState(null);
  const [formInput, setFormInput] = useState(
    {
      peso: 0,
      reps: 0,
      tipo: 'lbs'
    }
    );
  const [oneRepMax, setOneRepMax] = useState({});
  
  useEffect(() => {
    handleSesion()
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  }, [])

  const handleSesion = async () => {

    const { data, error } = await supabase.auth.getSession()

    if(data.session){
      setSesion(data.session);
      //console.log(data);
    } 
    else {
      setSesion(null);
    }
  }

  const handleOnInputChange = useCallback(
    (event) => {
      const { value, name, id, checked} = event.target;

      setFormInput({
        ...formInput,
        [name]: value,
      });

    },
    [formInput, setFormInput]
  );

  const calcularOneRepMax = (cambio) => {
    if (cambio) {
      if(oneRepMax.tipo == 'lbs'){
        let ORM100 = (oneRepMax.M100f * 0.45359237)
        setOneRepMax({
          M100f: ORM100,
          M100: Math.round(ORM100),
          M95: Math.round(ORM100 * 0.95),
          M90: Math.round(ORM100 * 0.90),
          M85: Math.round(ORM100 * 0.85),
          M80: Math.round(ORM100 * 0.80),
          M75: Math.round(ORM100 * 0.75),
          M70: Math.round(ORM100 * 0.70),
          M65: Math.round(ORM100 * 0.65),
          M60: Math.round(ORM100 * 0.60),
          M55: Math.round(ORM100 * 0.55),
          M50: Math.round(ORM100 * 0.50),
          tipo: 'kg'
        })
      }
      else{
        let ORM100 = (oneRepMax.M100f * 2.20462262185)
        setOneRepMax({
          M100f: ORM100,
          M100: Math.round(ORM100),
          M95: Math.round(ORM100 * 0.95),
          M90: Math.round(ORM100 * 0.90),
          M85: Math.round(ORM100 * 0.85),
          M80: Math.round(ORM100 * 0.80),
          M75: Math.round(ORM100 * 0.75),
          M70: Math.round(ORM100 * 0.70),
          M65: Math.round(ORM100 * 0.65),
          M60: Math.round(ORM100 * 0.60),
          M55: Math.round(ORM100 * 0.55),
          M50: Math.round(ORM100 * 0.50),
          tipo: 'lbs'
        })
      }
    }
    else{
      let ORM100 = formInput.peso * ( 1 + (formInput.reps / 30))
      setOneRepMax({
        M100f: ORM100,
        M100: Math.round(ORM100),
        M95: Math.round(ORM100 * 0.95),
        M90: Math.round(ORM100 * 0.90),
        M85: Math.round(ORM100 * 0.85),
        M80: Math.round(ORM100 * 0.80),
        M75: Math.round(ORM100 * 0.75),
        M70: Math.round(ORM100 * 0.70),
        M65: Math.round(ORM100 * 0.65),
        M60: Math.round(ORM100 * 0.60),
        M55: Math.round(ORM100 * 0.55),
        M50: Math.round(ORM100 * 0.50),
        tipo: formInput.tipo
      })
    }
  }

  return (
    <div className="bg-stone-100 w-full" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        
        <div className="w-11/12 md:w-9/12 mx-auto max-w-5xl">
          <h2 className="text-2xl font-bold">Máximo Peso para una Repetición</h2>
          <h3 className="text-xl">One Rep Max</h3>

          <p className="text-lg font-bold">Peso</p>
          <span className="p-4 bg-white rounded-lg">
            <input className="py-3.5 w-16 rounded-lg outline-none" type="number" value={formInput.peso || ""} onChange={handleOnInputChange} placeholder="" name="peso" id="peso" />
            <span>{' ' + formInput.tipo}</span>
          </span>
          <button className="btn" onClick={handleOnInputChange} name="tipo" id="lbs" value="lbs">
            lbs
          </button>
          <button className="btn" onClick={handleOnInputChange} name="tipo" id="kg" value="kg">
            kg
          </button>

          <p className="text-md font-bold">Repeticiones</p>
          <input className="input" type="number" value={formInput.reps || ""} onChange={handleOnInputChange} placeholder="" name="reps" id="reps" />

          <br/>
          <button className="btn" onClick={()=>{calcularOneRepMax(false)}}>Calcular</button>

          { oneRepMax.M100 ? 
            <div className="relative overflow-x-auto">
              <p className="text-xl font-bold">One Rep Max</p>
              
              <button className="btn" onClick={()=>{calcularOneRepMax(true)}}>
                {oneRepMax.tipo == 'lbs' ?
                  'Cambiar a kg'
                  :
                  'Cambiar a lbs'
                }
              </button>

              <table className="w-full text-left text-gray-500 border-2 border-blue-500 bg-blue-200">
                <thead className="text-gray-700 uppercase">
                  <tr>
                    <th scope="col" className="px-6 py-3">{'Repeticiones'}</th>
                    <th scope="col" className="px-6 py-3">{'Peso (' + oneRepMax.tipo + ')'}</th>
                    <th scope="col" className="px-6 py-3">{'Porcentaje de 1RM'}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'1'}</td>
                    <td className="px-6 py-2">{oneRepMax.M100 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'100%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'2'}</td>
                    <td className="px-6 py-2">{oneRepMax.M95 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'95%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'4'}</td>
                    <td className="px-6 py-2">{oneRepMax.M90 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'90%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'6'}</td>
                    <td className="px-6 py-2">{oneRepMax.M85 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'85%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'8'}</td>
                    <td className="px-6 py-2">{oneRepMax.M80 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'80%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'10'}</td>
                    <td className="px-6 py-2">{oneRepMax.M75 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'75%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'12'}</td>
                    <td className="px-6 py-2">{oneRepMax.M70 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'70%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'16'}</td>
                    <td className="px-6 py-2">{oneRepMax.M65 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'65%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'20'}</td>
                    <td className="px-6 py-2">{oneRepMax.M60 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'60%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'24'}</td>
                    <td className="px-6 py-2">{oneRepMax.M55 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'55%'}</td>
                  </tr>
                  <tr scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    <td className="px-6 py-2">{'30'}</td>
                    <td className="px-6 py-2">{oneRepMax.M50 + ' ' + oneRepMax.tipo}</td>
                    <td className="px-6 py-2">{'50%'}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          :
            ''
          }
        </div>

        <br />
        <br />
        <br />
        <br />
        <br />
      </main>

      <br />

      <Footer></Footer>
    </div>
  );
}
