import React from "react";
import Navbar from "./Componentes/Navbar";
import Head from "next/head";
import {CheckIcon} from '@heroicons/react/solid'
import Precios from './Componentes/CardsPrecios';
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

const plans = [
  {
    nombre: '1 mes',
    precio: 149,
    frecuencia: 'mes',
    popular: false,
    caracteristicas: [
      'Facturado cada 3 meses',
      'El paquete más económico',
      'Obten todos los beneficios',
    ]
  },
  {
    nombre: '6 meses',
    precio: 126.65,
    frecuencia: 'mes',
    popular: true,
    caracteristicas: [
      'Facturado cada 6 meses',
      'Ahorra el 15%',
      'Obten todos los beneficios',
    ]
  },
  {
    nombre: '12 meses',
    precio: 104.30,
    frecuencia: 'mes',
    popular: false,
    caracteristicas: [
      'Facturado cada 12 meses',
      'Ahorra el 30%',
      'Obten todos los beneficios',
    ]
  },
]
  

export default function Home() {

  const router = useRouter();

  return (
    <div className="bg-blue-50 ">
      <Head>
        <title>EvoltFit - Precios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <h1 className="text-5xl text-center text-blue-700 italic font-bold ">
        {"Evolfit Plus"}
      </h1>
      <br />
      <br />
      <h1 className="text-4xl text-center font-bebas tracking-wider">
        {"Precios diseñados para tus objetivos"}
      </h1>
      <div className = "flex flex-col items-center">
      <button onClick={() => router.push("../registro")} className = "mt-12 w-64 py-4 px-8 rounded-lg text-xl whitespace-nowrap bg-blue-600 text-white hover:scale-110 transition-all font-catamaran">Registrate</button>
      </div>
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <div className="h-full px-6 py-12 lg:flex lg:justify-center lg:items-center">
      <div className = "grid lg:grid-cols-3 gap-12 lg:gap-0">
       {
        plans.map(plan =>(
          <div className = {`w-full max-w-md mx-auto ${plan.popular ? "order-first lg:order-none lg:scale-110 lg:transform lg:z-10" : "lg:transform lg:scale-90"}`}>
          <Precios {...plan} key = {plan.nombre}/>
          </div>
        ))
        }
        </div>
    </div>
    </div>
  );
}
