import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect, useCallback } from "react";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import CardRutina from "/components/CardRutina";
import supabase from "../config/supabaseClient";

export default function Progreso() {
  const router = useRouter();

  const [sesion, setSesion] = useState(null);
  const [setsProgreso, setSetsProgreso] = useState(null);
  
  useEffect(() => {
    handleSesion()
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  }, [])

  const handleSesion = async () => {

    const { data, error } = await supabase.auth.getSession()

    if(data.session){
      setSesion(data.session);
      getSetsProgreso(data.session);
      //console.log(data);
    } 
    else {
      setSesion(null);
      //console.log("No hay Sesión " + error);
      router.push('/login')
    }
  }

  async function getSetsProgreso(session) {
    const { data, error } = await supabase
    .from('progreso_sets')
    .select(`
    *,
    ejercicio(id, nombre)
    `)
    .eq('usuario', session.user.id)

    if (error) {
      console.log('ERROR: Hubo un error al recuperar el progreso.')
      console.log(error)
    }
    else{
      console.log(data);
      setSetsProgreso(data);
    }
  }


  return (
    <div className="bg-stone-100 w-full" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        
        <div>          
          {
            setsProgreso ? 
            <div className="mx-auto mt-6">
              <button className="btn btn-ghost m-0 px-2 text-lg" onClick={() => {router.push('/rutinas')}}>
                <div className='text-3xl mt-auto'>
                  <ion-icon name="arrow-back-outline"></ion-icon>
                </div>
                <span className="ml-2">{"Volver a Rutinas"}</span>
              </button>
              <div className="flex flex-col w-11/12 sm:w-9/12 mx-auto max-w-5xl">
                <h2 className="text-3xl sm:text-4xl p-2 text-secondary my-2 w-full font-semibold whitespace-nowrap text-ellipsis overflow-hidden">
                  {"Progreso de " + sesion.user.user_metadata.nombre}
                </h2>
                { setsProgreso.length === 0 ? 
                    <h2>{'Ups, aquí no hay setsProgreso. 🥵'}</h2>
                  :
                    (setsProgreso.map((set) => (
                        <div>
                          <span>
                            {
                            set.ejercicio.nombre
                            + ' | Reps: '
                            + set.reps
                            + ' | Peso: '
                            + set.peso
                            + ' | Tipo: '
                            + set.tipo_set
                            }
                          </span>
                        </div>
                      ))
                    )
                }
              </div>
            </div> 
            : 
            <div className="mt-12">
              <div className="loader mt-6"></div>
            </div>
          }
        </div>
        <br />
      </main>

      <br />

      <Footer></Footer>
    </div>
  );
}
