import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState, useEffect, useCallback } from 'react';
import Navbar from "./Componentes/Navbar";
import Footer from "./Componentes/Footer";
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();

  //console.log(supabase);
  const [fetchError, setFetchError] = useState(null);
  const [datos, setDatos] = useState(null);

  //----------------------------------------------------------------
  const [formInput, setFormInput] = useState({});
  const [errorDatosInput, setErrorDatosInput] = useState({});

  const handleOnInputChange = useCallback(
    (event) => {
      const { value, name } = event.target;

      setFormInput({
        ...formInput,
        [name]: value,
      });

      //VALIDACIÓN INPUT CORREO
      if (name == "correo"){
        var error = ['control'];
        var regexCorreo = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;        

        if (!regexCorreo.test(value)){
          error.push("error");
        }
    
        setErrorDatosInput({
          ...errorDatosInput,
          [name]: error,
        });
      }

      //VALIDACIÓN INPUT PASSWORD
      if (name == "password"){
        var error = ['control'];
        var regexPass = /^.{6,}$/;

        if (!regexPass.test(value)){
          error.push("error");
        }

        setErrorDatosInput({
          ...errorDatosInput,
          [name]: error,
        });
      }

      //VALIDACIÓN INPUT PASSWORD
      if (name == "confirmarPassword"){
        var error = ['control'];       

        if (formInput.password != value){
          error.push("error");
        }
    
        setErrorDatosInput({
          ...errorDatosInput,
          [name]: error,
        });
      }

    },
    [formInput, setFormInput]
  );

  //----------------------------------------------------------------
  const handleRegistro = async () => {

    if(formInput.correo != null){
      const { data, error } = await supabase.auth.signUp({
        email: formInput.correo,
        password: formInput.password,
      })

      if(error){
        setDatos(null);
        setFetchError('Error al conseguir datos');
        console.log("Error: " + error);
      } 
      else {
        setDatos(data);
        setFetchError(null);
        console.log("Registro exitoso :)");
      }
    }
  }

  function incluye(arreglo, buscar) {
    if (arreglo != undefined){
      var encontrado = false;
      var arreglo_temp = Array.from(arreglo);

      for (let i = 0; i < arreglo_temp.length; i++) {
        if (arreglo_temp[i] == buscar){
          encontrado = true;
          break;
        }
      }  
      return encontrado;
    }
    else{
      return false;
    }
  }

  return (
    <div className="bg-stone-100" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>

      <main className='flex flex-col content-center items-center'>
        <div className="form-control py-10 px-16 bg-white rounded-2xl shadow-lg w-1/2">
          <h2 className="text-3xl font-bold mb-10">
            Registro
          </h2>

          {/*CAMPO CORREO ---------------------------- */}
          <input name="correo" value={formInput.correo || ""} onChange={handleOnInputChange} type="text" placeholder="Correo" className={"input input-lg focus:border-secondary text-xl py-6 h-full font-normal rounded-xl shadow-md " +  (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error")  ? "input-error" : "input-success") : " ")}/>
          
          <label className="label">
            <span className="label-text-alt">
              {
                //(incluye(errorDatosInput.correo, "error")  ? "Use una dirección de correo válida." : "")
              }
            </span>
            <span className="label-text-alt text-lg font-light text-red-500 mb-4">{incluye(errorDatosInput.correo, "error")  ? "Use un correo válido." : ""}</span>
          </label>

          {/*CAMPO CONTRASEÑA ------------------------ */}
          <input name="password" value={formInput.password || ""} onChange={handleOnInputChange} type="password" placeholder="Contraseña" className={"input input-lg focus:border-secondary text-xl py-6 h-full font-normal rounded-xl shadow-md " +  (incluye(errorDatosInput.password, "control")  ? (incluye(errorDatosInput.password, "error")  ? "input-error" : "input-success") : " ")}/>
          
          <label className="label">
            <span className="label-text-alt">
              {
                //(incluye(errorDatosInput.correo, "error")  ? "Use una dirección de correo válida." : "")
              }
            </span>
            <span className="label-text-alt text-lg font-light text-red-500 mb-4">{incluye(errorDatosInput.password, "error")  ? "La contraseña es demasiado corta" : ""}</span>
          </label>

          {/*CAMPO CONFIRMAR CONTRASEÑA -------------- */}
          <input name="confirmarPassword" value={formInput.confirmarPassword || ""} onChange={handleOnInputChange} type="password" placeholder="Confirmar Contraseña" className={"input input-lg focus:border-secondary  text-xl py-6 h-full font-normal rounded-xl shadow-md " + (incluye(errorDatosInput.confirmarPassword, "control")  ? (incluye(errorDatosInput.confirmarPassword, "error")  ? "input-error" : "input-success") : " ")}/>
        
          <label className="label">
            <span className="label-text-alt">
              {
                //(incluye(errorDatosInput.correo, "error")  ? "Use una dirección de correo válida." : "")
              }
            </span>
            <span className="label-text-alt text-lg font-light text-red-500 mb-4">{incluye(errorDatosInput.confirmarPassword, "error")  ? "Las contraseñas no coinciden." : ""}</span>
          </label>
              
          {
            (datos) ? 
            (
              <div className="alert alert-success font-bold text-white">
                <div>
                  <span>
                    ¡Se envió un correo de verificación!
                  </span>
                </div>
              </div>
            )
            : ""
          }

          {
            (fetchError) ? 
            (
              <div className="alert alert-error font-bold text-white">
                <div>
                  <span>
                    Ocurrió un error.
                  </span>
                </div>
              </div>
            )
            : ""
          }
          
          <div className="divider mb-8 mt-2"></div>

          {/*BOTÓN ENVIAR FORMULARIO ---------------- */}
          <button className={"btn btn-secondary btn-lg " + (incluye(errorDatosInput.correo, "control")  ? (incluye(errorDatosInput.correo, "error") || incluye(errorDatosInput.password, "error") || incluye(errorDatosInput.confirmarPassword, "error") ? "btn-disabled" : " ") : " ")} onClick={handleRegistro}>Registrarse</button>

          <a className="link link-secondary self-end mt-8 text-xl font-light" onClick={() => router.push('/login')}>¿Ya tienes cuenta? Inicia sesión</a>
        </div>

        <button
          onClick={() => router.push('/')}
          className="btn btn-ghost text-2xl font-normal p-10 mt-10 content-center"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
          &nbsp;Volver al Inicio
        </button>
      </main>

      <br/>
      <br/>
      <Footer/>
    </div>
  );
}
