import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState, useEffect, useCallback } from 'react';
import supabase from '../config/supabaseClient';

export default function Home() {
  const router = useRouter();

  //console.log(supabase);
  const [fetchError, setFetchError] = useState(null);
  const [datos, setDatos] = useState(null);

  //----------------------------------------------------------------
  const [formInput, setFormInput] = useState({});
  const [errorDatosInput, setErrorDatosInput] = useState({});

  const handleOnInputChange = useCallback(
    (event) => {
      const { value, name } = event.target;

      setFormInput({
        ...formInput,
        [name]: value,
      });

      //VALIDACIÓN INPUT CORREO
      if (name == "correo"){
        var error = ['control'];
        var regex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;        

        if (!regex.test(value)){
          error.push("error");
        }
    
        setErrorDatosInput({
          ...errorDatosInput,
          [name]: error,
        });
      }

      //VALIDACIÓN INPUT PASSWORD
      if (name == "password"){

      }

      //VALIDACIÓN INPUT PASSWORD
      if (name == "confirmarPassword"){
        var error = ['control'];       

        if (formInput.password != value){
          error.push("error");
        }
    
        setErrorDatosInput({
          ...errorDatosInput,
          [name]: error,
        });
      }

    },
    [formInput, setFormInput]
  );

  //----------------------------------------------------------------
  /*
  useEffect(() => {
    const fetchDatos = async () => {
      const { data, error } = await supabase
        .from('usuarios_prueba')
        .select()

        if(error){
          setFetchError('Error al conseguir datos');
          setDatos(null);
          console.log(error);
        }
        if(data){
          setDatos(data);
          setFetchError(null);
        }
    }

    fetchDatos();
  }, [])
  */

  const handleRegistro = async () => {

    const { data, error } = await supabase.auth.signUp({
      email: formInput.correo,
      password: formInput.password,
    })

    if(error){
      setFetchError('Error al conseguir datos');
      setDatos(null);
      console.log(error);
    }
    if(data){
      setDatos(data);
      setFetchError(null);
      console.log(data);
    }
  }

  function incluye(arreglo, buscar) {
    if (arreglo != undefined){
      var encontrado = false;
      var arreglo_temp = Array.from(arreglo);

      for (let i = 0; i < arreglo_temp.length; i++) {
        if (arreglo_temp[i] == buscar){
          encontrado = true;
          break;
        }
      }  
      return encontrado;
    }
    else{
      return false;
    }
  }

  //console.log(datos);
  //console.log(fetchError);

  return (
    <div className={styles.container}>
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className="font-thin text-2xl">
          Registro
        </h2>

        <div className="form-control w-full max-w-xs border-double border-4 p-6 m-6 border-gray-700 rounded-lg">
          {/*CAMPO CORREO ---------------------------- */}
          <label className="label">
            <span className="label-text mt-4">{"Correo"}</span>
          </label>
          <input name="correo" value={formInput.correo || ""} onChange={handleOnInputChange} type="text" placeholder="Correo" className={"input input-bordered w-full max-w-xs " + (incluye(errorDatosInput.correo, "error")  ? "input-error" : " ")}/>
          
          <label className="label">
            <span className="label-text-alt">
              {
                //(incluye(errorDatosInput.correo, "error")  ? "Use una dirección de correo válida." : "")
              }</span>
            <span className="label-text-alt text-red-500 m-0">{incluye(errorDatosInput.correo, "error")  ? "Usar un correo válido." : ""}</span>
          </label>

          {/*CAMPO CONTRASEÑA ------------------------ */}
          <label className="label">
            <span className="label-text">{"Contraseña"}</span>
          </label>
          <input name="password" value={formInput.password || ""} onChange={handleOnInputChange} type="password" placeholder="Contraseña" className={"input input-bordered w-full max-w-xs " + (incluye(errorDatosInput.password, "error")  ? "input-error" : " ")}/>
        
          {/*CAMPO CONFIRMAR CONTRASEÑA -------------- */}
          <label className="label">
            <span className="label-text mt-4">{"Confirmar Contraseña"}</span>
          </label>
          <input name="confirmarPassword" value={formInput.confirmarPassword || ""} onChange={handleOnInputChange} type="password" placeholder="Confirmar Contraseña" className={"input input-bordered w-full max-w-xs " + (incluye(errorDatosInput.confirmarPassword, "error")  ? "input-error" : " ")}/>
        
          <label className="label">
            <span className="label-text-alt">
              {
                //(incluye(errorDatosInput.correo, "error")  ? "Use una dirección de correo válida." : "")
              }</span>
            <span className="label-text-alt text-red-500">{incluye(errorDatosInput.confirmarPassword, "error")  ? "Las contraseñas no coinciden." : ""}</span>
          </label>

          {/*BOTÓN ENVIAR FORMULARIO ---------------- */}
          <button className="btn btn-outline btn-success rounded-full m-4" onClick={handleRegistro}>Iniciar Sesión</button>
        </div>

        <button
          onClick={() => router.push('/login')}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-10"
        >
          Login
        </button>

        <button
          onClick={() => router.push('/')}
          className="btn btn-info btn-outline btn-wide btn-md rounded-full my-0"
        >
          Inicio
        </button>
      </main>

      <footer className={styles.footer}>
        <p className="font-light">
          {'Powered by '}
          <span className="animate-pulse font-bold text-fuchsia-500">
            {'Evoltfit'}
          </span>
        </p>
      </footer>
    </div>
  );
}
