import React, { useEffect, useState } from 'react';

import { useRouter } from "next/router";
import Navbar from './Componentes/Navbar';
import Footer from "./Componentes/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  //Variables generales
  const [series, setSeries] = useState("3");
  const [repeticiones, setRepeticiones] = useState("12");
  const [descanso, setDescanso] = useState("3m");
  //Recuperar valores
  const router = useRouter();
  const { formData2, checkboxes, arreglo } = router.query;
  //JSON
  const formulario = JSON.parse(formData2);
  const herramientas = JSON.parse(checkboxes);
  const opciones = JSON.parse(arreglo);
  //contenidos de puede llegar a contener cada dia
  const contenido1 = ['1', '1', '1', '1', '1'];//lUNES
  const contenido2 = ['2', '2', '2', '2', '2', '2'];//MARTES
  const contenido3 = ['3', '3', '3', '3'];//MIERCOLES
  const contenido4 = ['4', '4', '4', '4', '4', '4'];//JUEVES
  const contenido5 = ['5', '5', '5', '5', '5'];//VIERNES
  const contenido6 = ['6', '6', '6', '6', '6', '6'];//SABADO


  //INICIO DEL SE


















  //una vez lleno el contenido se une todo para mostrarlo en la tabla
  const arrays = [contenido1, contenido2, contenido3, contenido4, contenido5, contenido6];
  const longestArray = arrays.reduce((a, b) => (a.length > b.length ? a : b));
  
  const handleClick = () => {
    console.log(formulario);
    console.log("posicion 2" + opciones[2]);
    console.log(herramientas);
    console.log(opciones);
  };

  useEffect(() => {
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  }, [])


  return (
    <div className="bg-blue-100 w-full h-screen">
      <Head>
        <title>EvoltFit - Sistema Experto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <br /><br />

        <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
          <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                <th className="px-6 py-3">Lunes</th>
                <th className="px-6 py-3">Martes</th>
                <th className="px-6 py-3">Miércoles</th>
                <th className="px-6 py-3">Jueves</th>
                <th className="px-6 py-3">Viernes</th>
                <th className="px-6 py-3">Sábado</th>
                <th className="px-6 py-3">Domingo</th>
              </tr>
            </thead>
            <tbody>
              {longestArray.map((_, index) => (
                <tr key={`${arrays[index]}-${index}`} className="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                  {arrays.map((array) => (
                    
                    <td key={array[index]} className="px-6 py-4">
                      {index < array.length ? 
                      <p>
                      {array[index]} <br/> 
                      <img src="img/completo2.png" alt='hola' style={{ width: '50px', height: '50px' }}></img>
                      <br/>{series}x{repeticiones} <br/> 
                      Descanso: {descanso}
                      </p>
                      : ''} <br />
</td>

                  ))}
                  <td key={index} className="px-6 py-4"></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>


        <button onClick={handleClick} className="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">ver Datos</button>
      <br/><br/> <br/> <br/> <br/> <br/> <br/>          
      </main>
      <Footer></Footer>
    </div>
  );
}