import React from 'react';
import { useRouter } from "next/router";
import Navbar from './Componentes/Navbar';
import Footer from "./Componentes/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();
  const { formData2, checkboxes, arreglo } = router.query;

  const handleClick = () => {
    console.log(JSON.parse(formData2));
    console.log(JSON.parse(checkboxes));
    console.log(JSON.parse(arreglo));
  };
  
  return (
    <div className="bg-blue-100 w-full h-screen">
      <Head>
        <title>EvoltFit - Sistema Experto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
      <button onClick={handleClick} className="text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">ver Datos</button>

      </main>
      <Footer></Footer>
    </div>
  );
}