import React , { useState, useEffect } from 'react';
import Navbar from './Componentes/Navbar';
import Footer from "./Componentes/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Seccion1 from "./SistemaE/Seccion1";
import Seccion2 from "./SistemaE/Seccion2";
import Seccion3 from "./SistemaE/Seccion3";
export default function Home() {
 
  const [value, setValue] = useState(0);
  const [formData, setFormData] = useState({});
  const [showButton, setShowButton] = useState(false);

  let element;
  
 

  function handleNext() {
    if (value < 2) {
      setValue(value+1);
    }
  }

  function handlePrevious() {
    if (value > 0) {
      setValue(value-1);
    }
  }
  //en los parametros recibo el name si quiero
  const handleChange = (value) => {
    setFormData({
      ...formData, value
    });
  setShowButton(true);
  }
  //cambiar de componentes
  if (value === 0) {
    element = <Seccion1 onChange={handleChange}/>;
    //element = <p>Componente A</p>;
  } else if (value === 1) {
    element = <Seccion2 />;
    //element = <p>Componente B</p>;
  } else {
    element = <Seccion3 />;
    //element = <p>Componente C</p>;
  }
  
  useEffect(() => {
    console.log(formData);
  }, [formData]);

    return (
      <div className = "bg-blue-100 w-full h-screen">
        <Head>
          <title>EvoltFit - Sistema Experto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        
        <main className={styles.main}>

        <div className={styles.seccion}>
        <h1>{element}</h1>
        </div>

        <div className='si'>
        {/*<button className="btn btn-outline rounded-full btn-secondary btn-lg m-8" onClick={handlePrevious}>Anterior</button>*/}
        {showButton ? (
        <button className="btn btn-outline rounded-full btn-secondary btn-lg m-8" onClick={handleNext}>Siguiente</button>
        ) : (
        <button>Siguiente</button>
        )}
        
        </div>

        </main>
        <Footer></Footer>
      </div>
    );
  }