import React , { useState } from 'react';
import Navbar from './Componentes/Navbar';
import Footer from "./Componentes/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Seccion1 from "./SistemaE/Seccion1";
import Seccion2 from "./SistemaE/Seccion2";
import Seccion3 from "./SistemaE/Seccion3";
export default function Home() {
 
  const [value, setValue] = useState(0);

  let element;
  if (value === 0) {
    element = <Seccion1 />;
    //element = <p>Componente A</p>;
  } else if (value === 1) {
    element = <Seccion2 />;
    //element = <p>Componente B</p>;
  } else {
    element = <Seccion3 />;
    //element = <p>Componente C</p>;
  }


  function handleNext() {
    if (value < 2) {
      setValue(value+1);
    }
  }

  function handlePrevious() {
    if (value > 0) {
      setValue(value-1);
    }
  }

  
    return (
      <div className = "bg-blue-100 w-full h-screen">
        <Head>
          <title>EvoltFit - Sistema Experto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        
        <main className={styles.main}>

        <div className='SI'>
        <h1>{element}</h1>
        </div>

        <button onClick={handlePrevious}>Anterior</button>
        <button onClick={handleNext}>Siguiente</button>

        </main>
        <Footer></Footer>
      </div>
    );
  }