import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Navbar from "/components/Navbar";
import supabase from "../config/supabaseClient";
import Footer from "/components/Footer";
import Link from "next/link";

export default function VisualizadorProgreso() {
  const router = useRouter();
  const [sesion, setSesion] = useState(null);
  const [flag, setFlag] = useState(false);
  const [resultado, setResultado] = useState(null);

  useEffect(() => {
    handleSesion();
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  }, []);

  const handleSesion = async () => {
    const { data, error } = await supabase.auth.getSession();

    if (data.session) {
      setSesion(data.session);
      //console.log(data);
    } else {
      setSesion(null);
      //console.log("No hay Sesión " + error);
    }
  };

  return (
    <div className="bg-stone-100 w-full" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

        <div className="container">
          <h1 className="text-3xl font-semibold text-center text-blue-600 lg:text-4xl">
            Sigue tu progreso
          </h1>
        </div>

       
          <div className="grid grid-cols-1 gap-y-16 mt-16 lg:grid-cols-2 place-items-center">

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 rounded-md shadow-2xl">
            <div className="grid place-items-center p-10">
              <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                Bienvenido a{" "}
                <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                  EvoltFit
                </span>
              </h1>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Selecciona un músculo del modelo y busca los ejercicios que
                mejor te acomoden.
              </h2>
              <span className="text-black text-xl font-semibold mt-3">
                O también...
              </span>
              <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
              <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                Puedes dejarnos todo el trabajo a nosotros y crearemos la mejor
                rutina para ti.
              </h2>
              <div className="flex flex-col mt-6 space-y-3 lg:space-y-0 lg:flex-row">
                <Link href="/sistemaexperto">
                  <a className="block px-6 py-2.5 text-sm font-medium tracking-wider text-center text-white uppercase transition-colors duration-300 transform bg-blue-600 rounded-md hover:bg-gray-700">
                    Vamos
                  </a>
                </Link>
              </div>
            </div>
            </div>

          </div>
         
        <br />
        <br />
        <br />
        <br />
      </main>

      <Footer />
    </div>
  );
}
