import Head from "next/head";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Navbar from "/components/Navbar";
import supabase from "../config/supabaseClient";
import Footer from "/components/Footer";
import Link from "next/link";

export default function VisualizadorProgreso() {
  const router = useRouter();
  const [sesion, setSesion] = useState(null);
  const [flag, setFlag] = useState(false);
  const [resultado, setResultado] = useState(null);

  useEffect(() => {
    handleSesion();
    localStorage.removeItem("NombrePaquete");
    localStorage.removeItem("Meses");
  }, []);

  const handleSesion = async () => {
    const { data, error } = await supabase.auth.getSession();

    if (data.session) {
      setSesion(data.session);
      //console.log(data);
    } else {
      setSesion(null);
      //console.log("No hay Sesión " + error);
    }
  };

  return (
    <div className="bg-stone-100 w-full" data-theme="emerald">
      <Head>
        <title>EvoltFit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

        <div className="container">
          <h1 className="text-3xl font-semibold text-center text-blue-600 lg:text-4xl">
            Sigue tu progreso
          </h1>
        </div>

       
          <div className="grid grid-cols-2 gap-2xl h-full ml-11 mr-11 p-5">
            <div className="border-blue-600 border-2 w-11/12 mt-6 mb-6 rounded-md shadow-2xl">
              <div className="h-12/12"></div>
            </div>

            <div className="border-blue-600 border-2 w-11/12 mt-6 mb-6 rounded-md shadow-2xl">
              <div className="grid place-items-center p-10">
                <h1 className="text-center text-2xl text-black xl:text-3xl font-semibold">
                  Prueba{" "}
                  <span className="text-blue-600 text-2xl xl:text-3xl italic font-bold font-catamaran">
                    Prueba
                  </span>
                </h1>
                <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                  Prueba Prueba Prueba Prueba Prueba Prueba Prueba Prueba Prueba
                  Prueba Prueba Prueba Prueba
                </h2>
                <span className="text-black text-xl font-semibold mt-3">
                  O también...
                </span>
                <span className="inline-block w-44 xl:w-60 h-1 bg-blue-500 rounded-full mt-3"></span>
                <h2 className="mt-5 text-xl text-black text-center xl:pl-20 xl:pr-20">
                  Prueba Prueba Prueba Prueba Prueba Prueba Prueba Prueba Prueba
                </h2>
              </div>
            </div>
          </div>
        
        <br />
        <br />
        <br />
        <br />
      </main>

      <Footer />
    </div>
  );
}
