import { useState, useEffect } from "react";
import { useRouter } from 'next/router';
import Head from "next/head";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import supabase from "/config/supabaseClient";

export default function visualizadorCalorias() {

  const router = useRouter();

  const [sesion, setSesion] = useState(null);
  const [flag, setFlag] = useState(false);
  const [resultado, setResultado] = useState(null);

  const handleSesion = async () => {
    const { data, error } = await supabase.auth.getSession();

    if (data.session) {
      setSesion(data.session);
      //console.log(data);
    } else {
      setSesion(null);
      //console.log("No hay Sesión " + error);
    }
  };



  return (
    <div className="bg-blue-50 w-full">
      <Head>
        <title>EvoltFit - Calculadora de Calorías</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <div className="flex flex-col items-center">
          <button className="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={() => {router.push("/agregarProducto")}}>Agregar producto</button>
        </div>
        <br />
        <div className="flex flex-col items-center">
          <button className="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={() => {router.push("/addCalorias")}}>Calcular calorías</button>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        
        <Footer></Footer>
      </main>
    </div>
  );
}
